language: node_js
node_js:
  - 'node'
  - 'lts/*'

env:
  - TYPESCRIPT=latest
  - TYPESCRIPT=3.7
  - TYPESCRIPT=3.1.3

before_install:
  - npm install typescript@$TYPESCRIPT

install: npm install

script:
  - npm test

cache: npm
